name: Run Unit Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure to have your dependencies listed in requirements.txt
          pip install pytest  # Install pytest if it's not in your requirements file

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run tests with some common pytest flags
          
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results  
